--- 
abstract: ~
author: 
  - Ruslan Zakirov <ruz@bestpractical.com>
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: CPAN2RT
no_index: 
  directory: 
    - inc
    - t
requires: 
  CPAN::DistnameInfo: 0
  Email::Address: 0
  File::Spec: 0
  HTTP::Date: 0
  LWP::UserAgent: 0
  List::Compare: 0
  List::MoreUtils: 0
  perl: 5.8.3
version: 0.01
